language: java
install: true
addons:
  sonarcloud:
    organization: bakdata
    token:
      secure: RfH/EbIMdlyILuURtxvvKQ5HYF+GgHWp8RWeBPs17XFcRpIroAlx4/UJzzcOMfvGfk6ce1lrWT1WQyhW5g7fRL0SGKmq2hsDG3q00gfyTciVyGnF6XKNy4VhWA+EAuN6qU7U/dcWf8ttSlO2fxAQNifpn6PhAmjF3CLLUHkCfEbz01HOoaA/BtFJReWtfmLDWLcGgEz3lzWtiobujYwE86Fz6Ch2JjYIjqFkPyffUaCOXWjPkSOTOO4o+TspX9GlgT9aj8WR0xfECvpnKr6s3Gx/zX/dbulV3R2JfUSHelByi72V4e69PzCx0per4wSc6eZyUaVYo2RSaGC38eypXQwN7MZOX26HV+STTeaVNMHXveoOuFHvlop/aXKkxcDv4MGaIq7WwniJoAWwziBweZTnVtJbn+FvEBLCfpuSxMYAW3SKR63PN56oMisSdZEyjnsRXgasj15sUgHVBpEqVGQNXs39Xqi3TpRxoCeZaWKraZC1ZqcGL0OYxVD4l+YmNabXIMG9+JdtyWRjtytDZXMRa4Uxq/NPVR9gtOBbiGbliiedC5uFhR8gI2PqWNEVxlp60C1Daryi4nmW6c797z+VLSu3p7a3QFKDfUDDYxvMoN8DTl4A1x6BWopFUHFiGu/qXvfSy9uBUgt0McQW7YO9lLlUHzFDMJWbP0D+3Cs=
jdk:
- oraclejdk8
script:
- "./gradlew sonarqube"
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - ".gradle"
dd:
  secure: gg15S/5Wq+CTPcIPTAk2MvJNzI6b0AN+Rk+LwSEcbVZrw8QFZ7AKltuYC8S6C0a3Be5fI37CvXiD2Q7ZS0qBkTxjLOFNULdCNlzOW1EiECHDDjRjMRm9RjQMZnckPceiFFcm+xZ91jK6Rdu9guO/5WMIgCKVxebK9fPiJbNXZr8+tOvM/JmqWC0+Hds9pgp4QxLwnFt1sRD9zC2e4sUx/9EzSUzELK/UljuO2gVvdDohvjXGdiXOi16qzcMAVRU0tzo3Qg7sH0vyE55hOVeZrTTZPP4Epbl/HU9nZI3F0SJdU14TTW6wunlgQKJ6oPvOqb6cvYFTzhTcLar6GVGZnP6o60nX2Kktf8TwYzC5CasPN1Ijmgvs72cYt5aWsAkSOEGBUJUejG7mDuWxn1IysNJYUQFst6e8e44E5C3WeXD+eIt+6yz2Aol8BoOYhqHGKCFaIHAxzUxASs9JT/3aT3FeetIrvYLBp5F68tw9Z0mVrwoveX8Zs6St9XzqJ6Y4vjulmptNicvcAldeaBSJqI4asM0MlBzBF4KuFnlqwFd35fVmvA6txyUhVdFC7A3rrpGfeWsvCUT6+mmXZBaXY5Q3MFtLXFzYThHxo2JxD+NRgGrqWGLT8dOTIVmi/Hg7JnSuBeawuUYzjUIQvcKu0xp9p52cK92TsvSMNWPjOoI=
