language: java
install: true
addons:
  sonarcloud:
    organization: bakdata
    token: $SONAR_TOKEN
jdk:
- oraclejdk8
script:
- "./gradlew sonarqube"
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - ".gradle"
dd:
  secure: gg15S/5Wq+CTPcIPTAk2MvJNzI6b0AN+Rk+LwSEcbVZrw8QFZ7AKltuYC8S6C0a3Be5fI37CvXiD2Q7ZS0qBkTxjLOFNULdCNlzOW1EiECHDDjRjMRm9RjQMZnckPceiFFcm+xZ91jK6Rdu9guO/5WMIgCKVxebK9fPiJbNXZr8+tOvM/JmqWC0+Hds9pgp4QxLwnFt1sRD9zC2e4sUx/9EzSUzELK/UljuO2gVvdDohvjXGdiXOi16qzcMAVRU0tzo3Qg7sH0vyE55hOVeZrTTZPP4Epbl/HU9nZI3F0SJdU14TTW6wunlgQKJ6oPvOqb6cvYFTzhTcLar6GVGZnP6o60nX2Kktf8TwYzC5CasPN1Ijmgvs72cYt5aWsAkSOEGBUJUejG7mDuWxn1IysNJYUQFst6e8e44E5C3WeXD+eIt+6yz2Aol8BoOYhqHGKCFaIHAxzUxASs9JT/3aT3FeetIrvYLBp5F68tw9Z0mVrwoveX8Zs6St9XzqJ6Y4vjulmptNicvcAldeaBSJqI4asM0MlBzBF4KuFnlqwFd35fVmvA6txyUhVdFC7A3rrpGfeWsvCUT6+mmXZBaXY5Q3MFtLXFzYThHxo2JxD+NRgGrqWGLT8dOTIVmi/Hg7JnSuBeawuUYzjUIQvcKu0xp9p52cK92TsvSMNWPjOoI=
